import React, { useState } from 'react';
import { Link } from 'react-router-dom';

const Login: React.FC = () => {
  const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

      const handleSubmit = (e: React.FormEvent) => {
          e.preventDefault();
              // TODO: Implémenter la logique de connexion
                  console.log('Login attempt:', { email, password });
                    };

                      return (
                          <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
                                <div className="max-w-md w-full space-y-8">
                                        <div>
                                                  <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
                                                              Connexion à Ebeno
                                                                        </h2>
                                                                                  <p className="mt-2 text-center text-sm text-gray-600">
                                                                                              Ou{' '}
                                                                                                          <Link to="/register" className="font-medium text-blue-600 hover:text-blue-500">
                                                                                                                        créez un nouveau compte
                                                                                                                                    </Link>
                                                                                                                                              </p>
                                                                                                                                                      </div>
                                                                                                                                                              <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
                                                                                                                                                                        <div>
                                                                                                                                                                                    <label htmlFor="email" className="block text-sm font-medium text-gray-700">
                                                                                                                                                                                                  Email
                                                                                                                                                                                                              </label>
                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                        id="email"
                                                                                                                                                                                                                                                      name="email"
                                                                                                                                                                                                                                                                    type="email"
                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                className="mt-1 appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:z-10 sm:text-sm"
                                                                                                                                                                                                                                                                                                              placeholder="votre@email.com"
                                                                                                                                                                                                                                                                                                                            value={email}
                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                      <label htmlFor="password" className="block text-sm font-medium text-gray-700">
                                                                                                                                                                                                                                                                                                                                                                                                    Mot de passe
                                                                                                                                                                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                          id="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        name="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="mt-1 appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:z-10 sm:text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Votre mot de passe"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Se connecter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default Login;