// backend/src/services/exportService.ts
import { existsSync, readFileSync } from 'fs';
import path from 'path';
import AdmZip from 'adm-zip';
import { db } from '../db/knex';
import { logAudit } from './auditLogService';
import { logger } from '../utils/logger';

export interface ExportAuditContext {
  ip: string | null;
  userAgent: string | null;
  userEmail?: string | null;
}

// ============================================================
// ✅ i18n : textes du README (5 langues)
// ============================================================
type Lang = 'fr' | 'en' | 'es' | 'pt' | 'ar';

const SUPPORTED_LANGS: Lang[] = ['fr', 'en', 'es', 'pt', 'ar'];

const normalizeLang = (l?: string): Lang => {
  const code = (l || 'fr').split('-')[0].toLowerCase();
  return (SUPPORTED_LANGS.includes(code as Lang) ? code : 'fr') as Lang;
};

const README_STRINGS: Record<Lang, {
  title: string;
  description: string;
  noDescription: string;
  statistics: string;
  transcriptions: string;
  memos: string;
  collaborativeDocs: string;
  files: string;
  entities: string;
  summaries: string;
  comments: string;
  exportedOn: string;
  generatedBy: string;
  projectId: string;
  projectStatus: string;
  projectVisibility: string;
  projectCreatedAt: string;
}> = {
  fr: {
    title: 'Export du projet',
    description: 'Description',
    noDescription: 'Aucune description',
    statistics: 'Statistiques',
    transcriptions: 'Transcriptions',
    memos: 'Mémos',
    collaborativeDocs: 'Documents collaboratifs',
    files: 'Fichiers uploadés',
    entities: 'Entités extraites',
    summaries: 'Résumés IA',
    comments: 'Commentaires',
    exportedOn: 'Export effectué le',
    generatedBy: 'Document généré automatiquement par Ebeno Research Platform',
    projectId: 'Identifiant',
    projectStatus: 'Statut',
    projectVisibility: 'Visibilité',
    projectCreatedAt: 'Créé le',
  },
  en: {
    title: 'Project export',
    description: 'Description',
    noDescription: 'No description',
    statistics: 'Statistics',
    transcriptions: 'Transcriptions',
    memos: 'Memos',
    collaborativeDocs: 'Collaborative documents',
    files: 'Uploaded files',
    entities: 'Extracted entities',
    summaries: 'AI summaries',
    comments: 'Comments',
    exportedOn: 'Exported on',
    generatedBy: 'Document automatically generated by Ebeno Research Platform',
    projectId: 'ID',
    projectStatus: 'Status',
    projectVisibility: 'Visibility',
    projectCreatedAt: 'Created on',
  },
  es: {
    title: 'Exportación del proyecto',
    description: 'Descripción',
    noDescription: 'Sin descripción',
    statistics: 'Estadísticas',
    transcriptions: 'Transcripciones',
    memos: 'Memos',
    collaborativeDocs: 'Documentos colaborativos',
    files: 'Archivos subidos',
    entities: 'Entidades extraídas',
    summaries: 'Resúmenes IA',
    comments: 'Comentarios',
    exportedOn: 'Exportado el',
    generatedBy: 'Documento generado automáticamente por Ebeno Research Platform',
    projectId: 'Identificador',
    projectStatus: 'Estado',
    projectVisibility: 'Visibilidad',
    projectCreatedAt: 'Creado el',
  },
  pt: {
    title: 'Exportação do projeto',
    description: 'Descrição',
    noDescription: 'Sem descrição',
    statistics: 'Estatísticas',
    transcriptions: 'Transcrições',
    memos: 'Memos',
    collaborativeDocs: 'Documentos colaborativos',
    files: 'Ficheiros carregados',
    entities: 'Entidades extraídas',
    summaries: 'Resumos IA',
    comments: 'Comentários',
    exportedOn: 'Exportado em',
    generatedBy: 'Documento gerado automaticamente por Ebeno Research Platform',
    projectId: 'Identificador',
    projectStatus: 'Estado',
    projectVisibility: 'Visibilidade',
    projectCreatedAt: 'Criado em',
  },
  ar: {
    title: 'تصدير المشروع',
    description: 'الوصف',
    noDescription: 'لا يوجد وصف',
    statistics: 'الإحصائيات',
    transcriptions: 'النسخ',
    memos: 'المذكرات',
    collaborativeDocs: 'المستندات التعاونية',
    files: 'الملفات المحمّلة',
    entities: 'الكيانات المستخرجة',
    summaries: 'ملخصات الذكاء الاصطناعي',
    comments: 'التعليقات',
    exportedOn: 'تم التصدير في',
    generatedBy: 'مستند تم إنشاؤه تلقائيًا بواسطة Ebeno Research Platform',
    projectId: 'المعرف',
    projectStatus: 'الحالة',
    projectVisibility: 'الظهور',
    projectCreatedAt: 'تم الإنشاء في',
  },
};

// ============================================================
// ✅ Helper : nom de fichier sûr et unique
// ============================================================
const safeName = (name: string, fallback: string = 'document', maxLen: number = 80): string => {
  const clean = (name || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')       // retire les accents
    .replace(/[^a-zA-Z0-9._-]/g, '_')      // remplace tout caractère spécial
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '')
    .substring(0, maxLen);
  return clean || fallback;
};

// ============================================================
// ✅ Helper : télécharge un fichier Cloudinary
// ============================================================
const downloadCloudinaryFile = async (url: string): Promise<Buffer | null> => {
  try {
    const response = await fetch(url);
    if (!response.ok) {
      logger.warn(`⚠️ [export] Cloudinary download échoué (${response.status}): ${url}`);
      return null;
    }
    const arrayBuffer = await response.arrayBuffer();
    return Buffer.from(arrayBuffer);
  } catch (err: any) {
    logger.warn(`⚠️ [export] Erreur téléchargement Cloudinary: ${err.message}`);
    return null;
  }
};

// ============================================================
// ✅ Helper : lire un fichier local ou télécharger Cloudinary
// ============================================================
const readFileContent = async (filePath: string): Promise<Buffer | null> => {
  if (!filePath) return null;

  // Cas 1 : URL Cloudinary
  if (filePath.startsWith('http://') || filePath.startsWith('https://')) {
    return downloadCloudinaryFile(filePath);
  }

  // Cas 2 : Chemin local (uploads/projects/xxx)
  const localPath = path.isAbsolute(filePath)
    ? filePath
    : path.join(__dirname, '../../', filePath);

  if (existsSync(localPath)) {
    try {
      return readFileSync(localPath);
    } catch (err: any) {
      logger.warn(`⚠️ [export] Lecture locale échouée: ${err.message}`);
    }
  }

  return null;
};

// ============================================================
// ✅ FONCTION PRINCIPALE
// ============================================================
export const exportProject = async (
  projectId: string,
  userId: string,
  auditContext?: ExportAuditContext
): Promise<Buffer> => {
  // 1. Vérifier l'autorisation
  const member = await db('project_members').where({ projectId, userId }).first();
  if (!member) throw new Error('Non autorisé');

  // 2. Récupérer le projet
  const project = await db('projects').where({ id: projectId }).first();
  if (!project) throw new Error('Projet non trouvé');

  // 3. Récupérer la langue du user
  const user = await db('users').where({ id: userId }).first();
  const lang = normalizeLang(user?.language);
  const S = README_STRINGS[lang];

  // 4. Récupérer toutes les données en parallèle
  const [
    transcriptions,
    memos,
    files,
    collabDocs,
    entities,
    summaries,
    comments,
  ] = await Promise.all([
    db('transcriptions').where({ projectId }).orderBy('createdAt', 'desc'),
    db('memos').where({ projectId }).orderBy('createdAt', 'desc'),
    db('project_files').where({ projectId }).orderBy('uploadedAt', 'desc'),
    db('collaboration_documents').where({ projectId }).orderBy('updatedAt', 'desc'),
    db('document_entities').whereIn(
      'documentId',
      db('transcriptions').where({ projectId }).select('id').union(
        db('memos').where({ projectId }).select('id').union(
          db('collaboration_documents').where({ projectId }).select('id')
        )
      )
    ).catch(() => []),
    db('document_summaries').whereIn(
      'documentId',
      db('transcriptions').where({ projectId }).select('id').union(
        db('memos').where({ projectId }).select('id').union(
          db('collaboration_documents').where({ projectId }).select('id')
        )
      )
    ).catch(() => []),
    db('comments')
      .whereIn(
        'documentId',
        db('transcriptions').where({ projectId }).select('id').union(
          db('memos').where({ projectId }).select('id').union(
            db('collaboration_documents').where({ projectId }).select('id')
          )
        )
      )
      .whereNull('deletedAt')
      .catch(() => []),
  ]);

  // 5. Créer le ZIP
  const zip = new AdmZip();
  const projectFolder = `projet_${safeName(project.title, 'projet')}`;

  // 5.1 Métadonnées
  const metadata = {
    project: {
      id: project.id,
      title: project.title,
      description: project.description,
      status: project.status,
      visibility: project.visibility,
      createdAt: project.createdAt,
      updatedAt: project.updatedAt,
    },
    exported_at: new Date().toISOString(),
    exported_by: user?.email || null,
    language: lang,
    stats: {
      transcriptions: transcriptions.length,
      memos: memos.length,
      collaborativeDocuments: collabDocs.length,
      files: files.length,
      entities: entities.length,
      summaries: summaries.length,
      comments: comments.length,
    },
  };
  zip.addFile(
    `${projectFolder}/metadata.json`,
    Buffer.from(JSON.stringify(metadata, null, 2), 'utf-8')
  );

  // 5.2 README (i18n)
  const statsLines = [
    `- ${S.transcriptions} : ${transcriptions.length}`,
    `- ${S.memos} : ${memos.length}`,
    `- ${S.collaborativeDocs} : ${collabDocs.length}`,
    `- ${S.files} : ${files.length}`,
    `- ${S.entities} : ${entities.length}`,
    `- ${S.summaries} : ${summaries.length}`,
    `- ${S.comments} : ${comments.length}`,
  ].join('\n');

  const readmeContent = `# ${S.title} : ${project.title}

## 📋 ${S.description}
${project.description || S.noDescription}

## 📊 ${S.statistics}
${statsLines}

## 📅 ${S.exportedOn}
${new Date().toISOString()}

---
${S.generatedBy}
`;

  zip.addFile(`${projectFolder}/README.md`, Buffer.from(readmeContent, 'utf-8'));

  // 5.3 Transcriptions
  if (transcriptions.length > 0) {
    transcriptions.forEach((t: any, idx: number) => {
      const suffix = idx > 0 ? `_${idx}` : '';
      const fileName = `${safeName(t.title, 'sans_titre')}${suffix}.txt`;
      const content = `${S.title}: ${t.title}
Status: ${t.status}
Language: ${t.language || 'inconnue'}
Date: ${t.createdAt}

---

${t.transcriptText || '(Aucun texte)'}`;
      zip.addFile(`${projectFolder}/transcriptions/${fileName}`, Buffer.from(content, 'utf-8'));
    });
  }

  // 5.4 Mémos
  if (memos.length > 0) {
    memos.forEach((m: any, idx: number) => {
      const suffix = idx > 0 ? `_${idx}` : '';
      const fileName = `${safeName(m.title, 'sans_titre')}${suffix}.txt`;
      const content = `${m.title}
Date: ${m.createdAt}
Language: ${m.language || 'inconnue'}

---

${m.content || '(Vide)'}`;
      zip.addFile(`${projectFolder}/memos/${fileName}`, Buffer.from(content, 'utf-8'));
    });
  }

  // 5.5 Documents collaboratifs
  if (collabDocs.length > 0) {
    collabDocs.forEach((doc: any, idx: number) => {
      const suffix = idx > 0 ? `_${idx}` : '';
      const fileName = `${safeName(doc.title, 'document')}${suffix}.txt`;
      const content = `${doc.title}
Version: ${doc.version}
Date: ${doc.updatedAt}

---

${doc.content || '(Vide)'}`;
      zip.addFile(`${projectFolder}/documents_collaboratifs/${fileName}`, Buffer.from(content, 'utf-8'));
    });
  }

  // 5.6 Fichiers uploadés (téléchargement Cloudinary)
  if (files.length > 0) {
    for (const f of files) {
      try {
        const buffer = await readFileContent(f.filePath);

        if (buffer) {
          const safeFileName = safeName(f.fileName, `fichier_${f.id}`);
          zip.addFile(`${projectFolder}/fichiers/${safeFileName}`, buffer);
        } else {
          const meta = `Fichier indisponible : ${f.fileName}
Taille : ${f.fileSize} octets
Type : ${f.mimeType}
URL : ${f.filePath}`;
          zip.addFile(
            `${projectFolder}/fichiers/${safeName(f.fileName, 'fichier')}.meta.txt`,
            Buffer.from(meta, 'utf-8')
          );
        }
      } catch (err: any) {
        logger.warn(`⚠️ [export] Erreur fichier ${f.fileName}: ${err.message}`);
      }
    }
  }

  // 5.7 Entités extraites (JSON global)
  if (entities.length > 0) {
    zip.addFile(
      `${projectFolder}/analyse/entities.json`,
      Buffer.from(JSON.stringify(entities, null, 2), 'utf-8')
    );
  }

  // 5.8 Résumés IA (JSON global)
  if (summaries.length > 0) {
    zip.addFile(
      `${projectFolder}/analyse/summaries.json`,
      Buffer.from(JSON.stringify(summaries, null, 2), 'utf-8')
    );
  }

  // 5.9 Commentaires (JSON global)
  if (comments.length > 0) {
    zip.addFile(
      `${projectFolder}/analyse/comments.json`,
      Buffer.from(JSON.stringify(comments, null, 2), 'utf-8')
    );
  }

  const zipBuffer = zip.toBuffer();

  // 6. Audit log
  if (auditContext) {
    try {
      await logAudit({
        userId,
        userEmail: auditContext.userEmail,
        action: 'project_exported',
        targetType: 'project',
        targetId: projectId,
        targetName: project.title,
        status: 'success',
        metadata: {
          sizeBytes: zipBuffer.length,
          stats: metadata.stats,
          language: lang,
        },
        ip: auditContext.ip,
        userAgent: auditContext.userAgent,
      });
    } catch (err: any) {
      logger.warn(`⚠️ [export] Audit log échoué: ${err.message}`);
    }
  }

  logger.info(
    `📦 [export] Projet "${project.title}" exporté (${(zipBuffer.length / 1024).toFixed(1)} KB) par ${userId}`
  );

  return zipBuffer;
};
